FROM public.ecr.aws/lambda/java:11

#RUN yum update -y \
#    && yum install -y libreoffice \
#    && yum install -y procps \
#    && yum clean packages

RUN yum update -y
RUN yum install -y libreoffice
RUN yum install -y procps \
    && yum clean packages

WORKDIR /
COPY build/libs/springboot-openoffice-demo-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "/app.jar", "public.ecr.aws/lambda/java:11"]
