FROM amd64/debian

RUN apt-get update -y \
    && apt-get install -y libreoffice \
    && apt-get install -y procps \
    && apt-get clean

WORKDIR /
COPY build/libs/springboot-openoffice-demo-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "/app.jar", "amd64/debian"]
